### ISSUE TITLE
Cannot find person through search

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#1124]
https://littlesis.org/person/1073-Philip_A_Laskawy

**Comment by Chad-Ballay** [comment]
![image](https://user-images.githubusercontent.com/29847796/87904530-1816c400-ca24-11ea-9af0-7ed763e47536.png)

Was able to find them when I searched.  Maybe there was a delay in indexing vs when you searched?  I believe this shows your issue as being resolved but please update with your response if my understanding is incorrect.

**Comment by aepyornis** [comment]
@Chad-Ballay Thanks. Yes, this issue appears to be resolved.
