### ISSUE TITLE
Option to create new entity when adding entities to list

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-rails#115]
If an entity isn't found in the add entity form/search, it would speed things up to allow a user to create a new entity right then and there, in a pop-out form.

**Comment by robjlucas** [comment]
E.g. like https://littlesis.org/person/67986-Boris_Johnson/add_relationship when entity not found

**Comment by robjlucas** [comment]
Use JSON create on app/controllers/entities_controller.rb
