### ISSUE TITLE
Flakey Codecov integration

### ISSUE THREAD

**Issue by robjlucas** [public-accountability/littlesis-rails#1187]
We are getting period meaningless test failures due to failures of communication between Travis and Codecov. Note the duplicated CI detection at the beginning, though this looks like a simple connectivity issue.

![Screenshot from 2020-07-16 12-47-13](https://user-images.githubusercontent.com/25692779/87667688-b96ef300-c762-11ea-933b-b2d8d5cfd7df.png)

**Comment by aepyornis** [comment]
I had switched to codecov not that long ago because the test coverage feature of codeclimate stopped working. I have no allegiances to any particular CI tool, so really anything that will reliably run `rspec`, `rubocop` and `simplecov` for us is fine by me.
