### ISSUE TITLE
Make this repo the root of the network graph

### ISSUE THREAD

**Issue by patcon** [public-accountability/littlesis-rails#133]
Would it be possible to somehow force this repo to occupy the root of the network graph?

It can be done if @skomputer deletes his/her repo, as explained [here](https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/#deleting-a-public-repository). It doesn't say exactly how it's chosen, but if it's reasonable, it'll take this one, the next fork below the original [on the network graph](https://github.com/skomputer/lilsis/network) :)

**Comment by aepyornis** [comment]
@skomputer is the original programmer of LittleSis who spent **years** working on the site, so I think we'll leave it forked as a sign of respect and awe! The [littlesis-rails network graph](https://github.com/public-accountability/littlesis-rails/network) is still informative, and it's always possible to use other git visualization tools.

**Comment by patcon** [comment]
While I understand and support the good intention (yay @skomputer!), I feel there are [other ways](https://github.com/kentcdodds/all-contributors) to reward a core developer :) But anyhow, I respect the decision, as it's your call.

(fwiw forks don't show up in GitHub search, for example)

**Comment by aepyornis** [comment]
@patcon btw, this has been done!
