### ISSUE TITLE
Sync with wikidata project

### ISSUE THREAD

**Issue by patcon** [public-accountability/littlesis-rails#134]
Has anyone had any discussions with folks from Wikimedia foundation about syncing littlesis data to/from their Wikidata database?

Seems like it would be a pretty good collaboration:
https://www.wikidata.org/wiki/Q27865661

Or in SPARQL query format: http://tinyurl.com/y9cvovh3

It would also mean that all the data could be alternatively visualized with other tools geared toward working with that platform: https://www.wikidata.org/wiki/Wikidata:Tools/External_tools

Here's a list of all the property types (some of which are inverse, which is nice), which might help determine whether the two system are compatible enough:
https://www.wikidata.org/wiki/Wikidata:List_of_properties/all

Anyhow, love the project, and thanks very very much for all your work on it! :)

**Comment by mrjohnc** [comment]
Hi all

I work a lot with Wikidata and have been thinking about how to integrate LittleSis data into Wikidata for a while. I work mainly on documentation and helping organisations work with Wikidata, I don't have a technical background and would have to find someone more technical to deal with actually moving the data. 

To me the main benefit I can see for LittleSis is that Wikidata includes links to Wikipedia articles and to entries for that subject in external databases on the subject e.g https://www.wikidata.org/wiki/Q1066551
This should help with research.

There would be other benefits including being able to run queries using Wikidata visualisation tools and creating 100,000s of links from Wikidata to LittleSis. 

I think importing data from LittleSis into Wikidata should be fairly straight forward, but will need some planning and decisions made on which data to include. The first questions I have are: 

- What data would you be interested in sharing on Wikidata? The minimum I can see possible would be the names of the people, organisations and their LittleSis urls
- Is there a page on LittleSis that describes the kinds of data held in LittleSis and the structure? 
- How do references work? Are there references for each statement made (how Wikidata works)
- Is some of the data on LittleSis automatically synched with other sources or is all manually added?
- How to export the data from LittleSis? Is there a way of getting spreadsheets?  
- What license does LittleSis use? 

Thanks

**Comment by patcon** [comment]
Cool! Thanks @mrjohnc! Calling this to @aepyornis' attention, as I think they're most qualified to answer :)

**Comment by pmackay** [comment]
I agree that connecting LittleSis and Wikidata is a useful goal, as a first step I've setup datasets on Mix n Match to reconcile entities the two platforms, by adding the [LittleSis organisation ID](https://www.wikidata.org/wiki/Property:P3393) and [LittleSis people ID](https://www.wikidata.org/wiki/Property:P3388) to Wikidata items. See

Orgs:
https://tools.wmflabs.org/mix-n-match/#/catalog/2897

People:
https://tools.wmflabs.org/mix-n-match/#/catalog/2899

**Comment by salgo60** [comment]
Would be nice to have the Wikidata Qnumber visible on littlesis its also more stable than the WIkipedia URL...

**Comment by mrjohnc** [comment]
Great this is being done, I have a suggestion on how to automatch a bigger
amount of items, currently there are way over 100,000 items to manually
match and this will take a really long time...

Many little Little Sis pages already have a link to Wikipedia, if we can
get an export of Little Sis that included the Wikipedia links we could
match these Wikipedia pages to their Wikidata items and so automatch
hopefully a large chunk of the work with good evidence that they are correct

If you're not sure how to do this I can help

**Comment by salgo60** [comment]
@mrjohnc if we get an export  with Wikipedia links then I think I can match them using [OpenRefine](https://github.com/OpenRefine/OpenRefine) or a python program...

I havnt checked the API littlesis have what is possible...

**Comment by carlinmack** [comment]
@magnusmanske how complex would it be to have something like The Distributed Game for this project?
