### ISSUE TITLE
Graph databases

### ISSUE THREAD

**Issue by patcon** [public-accountability/littlesis-rails#135]
Hi all! Sorry, new here and still getting acquainted.

Have there been any previous discussions about experimenting with graph databases like Neo4j in order to capitalize on tools already designed for visualizing graph data?

And related, if someone were interested in experimenting, might it be possible to get a database dump so that I could use the [RDBMS-to-Neo4j ETL Tool](https://neo4j.com/blog/rdbms-neo4j-etl-tool/) to try to get data into a format that would work with [Popoto.js](http://www.popotojs.com/)

**Comment by aepyornis** [comment]
Hey @patcon 

Delighted you are interested in the project. 

Yes, we've thought about experimenting with graph databases before. That Neo4J conversion tool will work (it's been tried before). I've been meaning to find the time to explore our data in Neo4j more thoroughly.

Popoto.js looks interesting. There's some code that exists already to generate networks graphs for entities in json that's buried in an old branch that's on my todo list to extract ( #43).
