### ISSUE TITLE
bulk upload tool improvements

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-rails#143]
a running list of possible improvements, which we can keep updating:
- is current should allow for selection of not current (three options)
- when you've selected a matching entity and want to clear the selection, icon should be an x (current symbol seems confusing)

**Comment by kconn** [comment]
- when you click upload on the add bulk page and it returns "something went wrong", it still does everything besides whatever produced the error. If you click upload again, it will add all that data again. If something goes wrong a) there should be better error reporting on what went wrong b) probably the whole thing should be voided, or you should be brought to a page with detail on whatever entity caused the error and everything else should be uploaded

**Comment by kconn** [comment]
- there should be some link back to the entity page from each add bulk page – maybe name and blurb should always be constant at the top, and linked? And the header "bulk add..." can be smaller

**Comment by aepyornis** [comment]
@kconn - I believe all of these issues have been addressed! check out the latest version on the site.
