### ISSUE TITLE
Problems with unescaping of search queries

### ISSUE THREAD

**Issue by robjlucas** [public-accountability/littlesis-rails#1438]
Some searches lead to exceptions due to the unescaping of double quotes here: https://github.com/public-accountability/littlesis-rails/blob/35ff753a77b4b27fc900ad3efc8e127281a6f94e/app/utility/ls_search.rb#L15

Example searches:

```
https://littlesis.org/oligrapher/find_nodes?num=20&q=Dr.+Cornelius+Packard+%22+Rhoads
https://littlesis.org/oligrapher/find_nodes?num=20&q=Dr.+Cornelius+Packard+y%22+Rhoads
https://littlesis.org/oligrapher/find_nodes?num=20&q=%22Grand+Slam
https://littlesis.org/oligrapher/find_nodes?num=20&q=Gilbert+%22Whip
```

Exception:

```
ThinkingSphinx::QueryExecutionError: index entity_core,entity_delta: syntax error, unexpected $end near '' - SELECT *, weight() * (link_count + 1) AS link_weight FROM `entity_core`, `entity_delta` WHERE MATCH('@(name,aliases,blurb) Dr. Cornelius Packard \" Rhoads') AND `is_deleted` = 0 AND `sphinx_deleted` = 0 ORDER BY `link_weight` DESC LIMIT 0, 20; SHOW META (Most recent call first)
```

**Comment by aepyornis** [comment]
The idea behind unescaping  **"** is to allow for users to use double quotes to search for exact matches. 

So it fails if you only include a single **"**, so ` "grand slam" ` works but  `"grand slam` errors. I wonder how we should handle this case

**Comment by robjlucas** [comment]
I suspect there is a way of enabling that sort of functionality in sphinx etc without needing to hand-crank it ourselves, and that would be more likely to handle such cases elegantly.

**Comment by aepyornis** [comment]
We use `ThinkingSphinx::Query.escape`, but that function will escape `"` 

`ThinkingSphinx::Query.escape('"example"')` => \"example\"
`LsSearch.escape('"example"')`=> '"example"'

**Comment by aepyornis** [comment]
There are a whole set of features to extended queries in sphinx https://docs.manticoresearch.com/3.4.0/html/searching/extended_query_syntax.html
