### ISSUE TITLE
Create a mark for merging or mark as duplicates function

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-rails#167]
This would basically work the same on the UI as the current merging tool, except the merge wouldn't actually happen until it was approved by some other (probably admin) user. This puts a check on merging so that incorrect merges, which can sometimes be hard to reverse/untangle, don't happen.

**Comment by kconn** [comment]
Of course, there would also need to be a "marked for merging" queue somewhere, probably on the backend.

**Comment by aepyornis** [comment]
related: #15
