### ISSUE TITLE
List title doesn't correctly encode quotes 

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#1673]
example: https://littlesis.org/lists/2999-jan-6-2021-stop-the-steal-trump-rally-speakers/members

**Comment by jessib** [comment]
To confirm, I think this is the place that is incorrect:

![image](https://github.com/public-accountability/littlesis-rails/assets/2983073/2f761f5b-7778-4c5d-9d4b-1f5215d38007)

**Comment by josephlacey** [comment]
Yeah, that's the symptom of the bad encoding that we saw earlier today.
