### ISSUE TITLE
Error attempting Entity merge

### ISSUE THREAD

**Issue by betsydupuis** [public-accountability/littlesis-rails#1696]
While attempting to merge the following entities, the merge returned the "Sorry! Something went wrong." page.
https://littlesis.org/person/428079-Peiter_Mudge_Zatko
https://littlesis.org/person/438507-Peiter_C._Zatko_aka_Mudge

These are the console errors.
<img width="824" alt="Screenshot 2024-06-22 at 11 36 27 PM" src="https://github.com/public-accountability/littlesis-rails/assets/2096627/6f934b4d-d292-435c-a4ec-fb46bf527a7d">

**Comment by aepyornis** [comment]
error was `EntityMerger::ConflictingExternalLinksError (Both entities have external links of type "twitter" with different values)` as in they had different twitter url but. I removed the wrong one and merged them.

**Comment by josephlacey** [comment]
Thanks @betsydupuis and @aepyornis!
