### ISSUE TITLE
Old Logo is on donation page

### ISSUE THREAD

**Issue by betsydupuis** [public-accountability/littlesis-rails#1708]
https://littlesis.ourpowerbase.net/civicrm/contribute/transact?reset=1&id=2
<img width="1282" alt="Screenshot 2024-07-13 at 4 09 05 PM" src="https://github.com/user-attachments/assets/a1e43505-c65e-4206-8bd4-7333341b3339">

**Comment by josephlacey** [comment]
@mooninmyname Here's the Github issue to update the logo on the Donation page.
