### ISSUE TITLE
Two different views exist for donate

### ISSUE THREAD

**Issue by betsydupuis** [public-accountability/littlesis-rails#1710]
There's two different donate views. It seems like a good opportunity to shrink the code base and fix the logo issue on both pages by deleting one of the duplicate views. 

**About / Donate**
https://littlesis.org/database/donate

**Donate Button**
https://littlesis.ourpowerbase.net/civicrm/contribute/transact?reset=1&id=2

**Comment by josephlacey** [comment]
Our donation page is hosted on a separate system, which is the raw, second one. The first URL is the alias we publish that uses our domain. In fact, https://littlesis.org/donate is a third, even shorter alias we use.  Nothing we can fix here even if the second one is a little confusing for folks.
