### ISSUE TITLE
Can't merge Beto

### ISSUE THREAD

**Issue by betsydupuis** [public-accountability/littlesis-rails#1718]
I tried to merge these two Betos. I got an error unable to merge

<img width="1210" alt="Screenshot 2024-07-23 at 1 35 43 PM" src="https://github.com/user-attachments/assets/b12dab57-fce5-4b73-a5b8-c0c73b5fa804">

**Comment by josephlacey** [comment]
We have some restrictions in place for merging records with large sets of resources associated with them.  We see this in the queue and will handle the merge.

**Comment by josephlacey** [comment]
> Weird, sometimes it lets me merge if I switch the order of the merge.

Indeed, this is usually the fix.  If both entities exceed the threshold, we'll have to figure out another solution.

**Comment by betsydupuis** [comment]
Maybe just a switch button. This is such a high level feature though, rarely used probably not worth fixing.
