### ISSUE TITLE
Only one location shows up on entity page

### ISSUE THREAD

**Issue by betsydupuis** [public-accountability/littlesis-rails#1719]
After adding an entity to the location tag field, only the first entity shows on the entity page.

**Comment by josephlacey** [comment]
@betsydupuis Can you attach a screenshot for this?

**Comment by betsydupuis** [comment]
Just edited on this page
https://littlesis.org/person/67072-Johnny_Depp

<img width="623" alt="Screenshot 2024-07-31 at 5 19 02 PM" src="https://github.com/user-attachments/assets/602c462f-239b-487f-93e2-b4a7ed03469f">
<img width="423" alt="Screenshot 2024-07-31 at 5 19 53 PM" src="https://github.com/user-attachments/assets/0d72a629-caaa-4308-8313-f54a37edcfb3">

**Comment by jessib** [comment]
This shows them all:
![image](https://github.com/user-attachments/assets/b0055765-3992-4b5e-bea9-117e81829b20)

I'm noticing some caching issues locally, such that the basic info doesn't reload unless I change something stored on the entity itself---is that worth looking into?

**Comment by josephlacey** [comment]
> I'm noticing some caching issues locally, such that the basic info doesn't reload unless I change something stored on the entity itself---is that worth looking into?

Probably not browser caching if it's only one section of the page.  I'd have to duplicate this if you want to open an issue.

**Comment by josephlacey** [comment]
Fixed by #1755

**Comment by jessib** [comment]
> > I'm noticing some caching issues locally, such that the basic info doesn't reload unless I change something stored on the entity itself---is that worth looking into?
> 
> Probably not browser caching if it's only one section of the page. I'd have to duplicate this if you want to open an issue.

I created https://github.com/public-accountability/littlesis-rails/issues/1756 after duplicating issue locally for locations, but did not yet check other associations.
