### ISSUE TITLE
Region field labeled as "location" in entity edit view

### ISSUE THREAD

**Issue by betsydupuis** [public-accountability/littlesis-rails#1721]
![image](https://github.com/user-attachments/assets/2493e344-fdec-4fb9-8ca3-456600b9e8f5)
![image](https://github.com/user-attachments/assets/6eb0b5df-2332-4b9b-ae52-b515dae0e03b)

**Comment by jessib** [comment]
Somebody should confirm the translations, but here is screenshot for en:
![image](https://github.com/user-attachments/assets/a13019d6-72ee-43ae-af7a-c38a03211367)

**Comment by josephlacey** [comment]
Fixed by #1754
