### ISSUE TITLE
Illegible help text on dashboard

### ISSUE THREAD

**Issue by betsydupuis** [public-accountability/littlesis-rails#1736]
It's hard to read the text "Map the Power Toolkit Re-vamp!" on the red background. Changing the text to white would be an easy fix.

<img width="393" alt="Screenshot 2024-08-22 at 2 17 06 PM" src="https://github.com/user-attachments/assets/065e8862-b98b-4d62-be02-4acbb6110bf5">

**Comment by josephlacey** [comment]
This makes sense.  PR created.  I'll push this a few other commits to the live site shortly.

I'm also inclined to change the background heading colors to match the new branding colors.  See the main website where most of the text color is white.

**Comment by betsydupuis** [comment]
Sure, especially is you can put them in a Sass variable. Branding consistency is definitely UX. There's studies that show that sites looks good are perceived to perform better.

**Comment by aepyornis** [comment]
those headings colors are editable by admins:

![screenshot-2024-09-25T11:40:31](https://github.com/user-attachments/assets/d0d396bb-f04c-4f45-abea-ccbff7866166)
