### ISSUE TITLE
Adding a featured image does not result in image featured on entity page.

### ISSUE THREAD

**Issue by betsydupuis** [public-accountability/littlesis-rails#1742]
Related to #1743

### Steps to reproduce
1. [Navigate to Entity Profile > Edit Image > Add](https://littlesis.org/entities/15108-Donald_Trump/images/new)
2. Chose file
3. Click "Is featured"
4. Click "Upload"
5. Image while be at the bottom of the list and be featured on the entity page.

<img width="1307" alt="Screenshot 2024-10-06 at 10 09 36 AM" src="https://github.com/user-attachments/assets/362a76a6-9f5d-4d96-ae8e-ec93b114e10e">

**Comment by josephlacey** [comment]
Seems like a minor bug that someone can manage manually, but also worth putting some effort into at some point to automatically unfeature an image if a new one is selected..

**Comment by josephlacey** [comment]
I guess this is the duplicate.  This will be fixed when #1743 is fixed.

**Comment by betsydupuis** [comment]
> I guess this is the duplicate. This will be fixed when #1743 is fixed.

I'm just being rigorous describing bugs in as small of units as possible to avoid assuming it's all the same problem.

This one is more about the checkbox not resulting in a featured image, the other one is more about the multiple featured images and confusing UI.
