### ISSUE TITLE
Bulk add matching system tweaks

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-rails#208]
When going through the matching process, page should scroll so that name/blurb from spreadsheet are visible – right now it's like the first image. The second image is better since it shows what you are matching with. Also it seems like there is a lot of blank screen, is that a bug?
![screen shot 2017-07-21 at 12 28 45 pm](https://user-images.githubusercontent.com/4164681/28472856-47912c66-6e10-11e7-99b0-a4f9c0484791.png)
![screen shot 2017-07-21 at 12 28 32 pm](https://user-images.githubusercontent.com/4164681/28472859-49772bfc-6e10-11e7-9d7e-67baf9a7a637.png)

**Comment by kconn** [comment]
When user clicks "view profile" it automatically selects that entity. It shouldn't select the entity until the user actually selects it.

**Comment by kconn** [comment]
there should probably be some way to skip forward or back without undoing matches – maybe I'm not seeing it

**Comment by kconn** [comment]
Might make sense to put select link next to name so it's clear how you select it. And when unselecting a previous match, keep the name searched for rather than turning it into a blank box.

**Comment by kconn** [comment]
would be good to show existing/similar relationships when selecting matches

**Comment by aepyornis** [comment]
#218 resolves some of these issues. the scrolling should work better, clicking on the link no longer causes a selection to be made. 

I've added a message to indicate that no entities where found (the primary reason you were seeing a big empty box) and made the box ever-so-slightly transparent.

**Comment by aepyornis** [comment]
made a separate issue for adding the similar relationships to the match mode: #219

**Comment by aepyornis** [comment]
If you click "Skip / Create New Entity" it skips that line. You can get out of the entire match mode by clicking 'cancel matching' at the top of the table. but yeah, there's no way to go back right now.
