### ISSUE TITLE
Update List Permissions [3]

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#210]
Lists can set to one of these three options: **OPEN, CLOSED, PRIVATE**

- Open lists are publicly editable and visible, where any _lister_ can edit them.
- Closed lists are publicly visible, but only editable by the list creator
- Private lists are only visible to the user who created them 

Additionally, admins can set a list as 'admin only' which supersedes the open or closed settings, making it so that only admin's can edit the list.

_Who can do what:_

-  Anyone with the _lister_ permission can edit any open list.
-  Only the list creator can change list settings (open/closed status, ranked, etc.)
-  Anyone can view any open or closed list
-  Any signed in user w/o lister permission can create lists, but cannot edit other lists. 
-  Admins, well, can basically do anything.

_Acceptance Criteria_

* Given no list
  * [x] any signed-in user can create a list of any status which they may then edit
* Given an open list
  * [x] all my view it
  * [x] a lister can add/remove entities + change description
  * [x] the owner can change the list settings
* Given a closed list
  * [x] all my view it
  * [x] a lister cannot edit it
  * [x] the owner can edit it and change the settings
* Given a private list
  * [x] only the owner can view and edit it
* [x] admins can do everything

Example mockup of list settings:

![listsettings](https://user-images.githubusercontent.com/8505044/28631686-11b56f18-71fc-11e7-8a9d-15ed26db24b7.png)

**Comment by aguestuser** [comment]
resolved by #213 
__________________

# Artifacts

**New Add List Page:**

![add-list-with-new-config](https://user-images.githubusercontent.com/6032844/29429034-33e53704-835d-11e7-95ce-7c95bea9dc13.png)

**New Edit List Page:**

![list-config-page-with-access-levels](https://user-images.githubusercontent.com/6032844/29429026-30d95540-835d-11e7-92ca-f81c0073a5df.png)
