### ISSUE TITLE
Add/remove tags on entity page  [5]

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#229]

**Comment by aguestuser** [comment]
* [ ] view/edit modes for tags
* [ ] click in textarea, see cursor in correct position 
* [ ] click in texteara with multiple lines, cursor is still in correct position
* [ ] autocomplete works
* [ ] dropdown works
* [ ] autocomplete selects stuff from dropdown

**Comment by aguestuser** [comment]
for deploy: only admins can see tags

**Comment by aguestuser** [comment]
pull in refactor of `last_user_id` into this card.

**Comment by aguestuser** [comment]
these are the available tags: https://pad.riseup.net/p/Mm3rfEWSxHMb
