### ISSUE TITLE
static tag overview page [1]

### ISSUE THREAD

**Issue by aguestuser** [public-accountability/littlesis-rails#232]
- describe what tags are
- llist and link to all tag homepages
- link to overview page from tag homepages

**Comment by aepyornis** [comment]
blocks #234

**Comment by aguestuser** [comment]
👍  i'll also use `tags_controller` for `tags/show` (assuming the admin page will be `tags/edit`?). 

are we worried about merge conflicts here, since we'll both be creating the same controller file and similar route entries?

**Comment by aepyornis** [comment]
For the admin tag i'm using the admin_controller, so we should have a problem. 

the route will be (for now at least)  /admin/tags -- i think it's easier to reason about all the admin pages together -- but we can revisit that later if it doesn't seem right.

**Comment by aepyornis** [comment]
@aguestuser  Although I will be need to create a tags_controllers for the create/edit new tag post routes...
