### ISSUE TITLE
Recent edits by tag [3]

### ISSUE THREAD

**Issue by aguestuser** [public-accountability/littlesis-rails#238]
# Acceptance Criteria

* if i visit the `philly` tag homepage I will see an `Edits` tab
* if i click on the `Edits` tab, i will see a paginated list of edits, sorted in reverse chronological order
* the edits tab has the following columns:
  * `Edited by` (user + timestamp), `Resource` (any Tagable) , `Description`,  `Action` (see below)
* possible actions include:
  * resource tagged/untagged/created/updated/deleted

# Implementation Notes

* updating a list means updating what members are in it
* updating an entity in a list does *not* update the list
* updating fields on an entity in a relationship does not update the relationship
* updating fields on a relationship *does* update entities

# Resolved by

#326, #366

**Comment by aguestuser** [comment]
(closing as resolved by #326 )

**Comment by kconn** [comment]
add user
