### ISSUE TITLE
sign up form – significant improvements needed [1]

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-rails#250]
in order of priority:
- All fields should be required and marked as such – many users are signing up without filling out the why they are signing up. 
- spam test should be captcha. math is too easy
- There should be a screen with a message after submitting the form that says the form was submitted successfully, with further instructions for logging in– check inbox for confirmation email, if it doesn't arrive file report or email us at this address. Right now it just brings you to a login page.
- newsletter signup phrasing is odd. This should be something like "Yes, sign me up for emails with news and updates from LittleSis! Emails are not very frequent – every 1-3 months."
- newsletter signup box should be checked by default
- email validation could be better. it's possible to signup with an email like al@dd

**Comment by aepyornis** [comment]
I think these are now the only things left to do for this:

- [ ] There should be a screen with a message after submitting the form that says the form was submitted successfully, with further instructions for logging in– check inbox for confirmation email, if it doesn't arrive file report or email us at this address. Right now it just brings you to a login page.

- [ ]   email validation could be better. it's possible to signup with an email like al@dd

**Comment by aepyornis** [comment]
I'm skipping changing the email validation for now. It's using the default html5 email validation which means that "user@site" is a valid email address. You can change the regular expression to a custom one, but I'm not sure that it's worth it.

see: https://stackoverflow.com/questions/19605773/html5-email-validation
