### ISSUE TITLE
Last edited by info on profile page not accurate [2]

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-rails#251]
Check this link: https://littlesis.org/org/254417-Massachusetts_Competitive_Partnership/edits
And attaching screenshot. Last edited by kevin but shows another user. Minor issue but a little confusing.
![screen shot 2017-08-05 at 10 37 33 am](https://user-images.githubusercontent.com/4164681/28996244-254c6d94-79ca-11e7-9213-125cfcfbbe10.png)

**Comment by aguestuser** [comment]
see #107

**Comment by aepyornis** [comment]
can't seem to reproduce this....

**Comment by aepyornis** [comment]
hopefully #516  has solved most of these issues.
