### ISSUE TITLE
Leverage federal contribution data to add employer relationships

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-rails#254]
Idea: After an individual has been donor-matched, go through names in employer field and identify some orgs that already exist in LittleSis, and then put those in a queue for the user to verify and add relationship data for. So if it says "Blackstone Group" and "Credit Suisse" in employer fields for different donations for the same person, queue those up for entry as relationships on some separate page.

**Comment by aepyornis** [comment]
wait for #759
