### ISSUE TITLE
Interlocks and data page doesn't work for Eagle Forum [2]

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#257]
* https://littlesis.org/org/89495/Eagle_Forum/interlocks

* https://littlesis.org/entities/89495-eagle-forum/relationships

**Comment by aguestuser** [comment]
this might produce another card related to a bigger issue, but that will be *out of scope* for *this* card, and we will estimate the "bigger issue" card separately.

**Comment by aepyornis** [comment]
Interlocks page had dangling links. #207 has solved this issue going forward, but we hadn't fixed older data.

we did:

1) removed those links for the eagle forum interlocks page
2) removed all dangling links in the database via mysql:

![delete_link_mysql](https://user-images.githubusercontent.com/8505044/29528322-a2a0bdee-8669-11e7-9c70-8e6c5d00be06.png)
