### ISSUE TITLE
Parent companies show up as child companies [2]

### ISSUE THREAD

**Issue by aguestuser** [public-accountability/littlesis-rails#259]
Molly:

> when i say johnson & johnson is the parent company it fills in that it is a child company

![parent-company-bug](https://user-images.githubusercontent.com/6032844/29281163-f21c2878-80eb-11e7-90c3-13948aa85853.png)

Gin
> did you do this using the extension? i had something similar happen but chalked it up to user error

Kevin
> i think i've come across that before

**Comment by aguestuser** [comment]
definition of done: figure out why this is happening. (fixing it might be separate card.)

**Comment by kconn** [comment]
bumping this. additionally, parent should be on top in the form instead of child.

**Comment by kconn** [comment]
In the past, if there were no descriptions added, entity 1 would default to parent and entity 2 would default to child (the logic of this is that the directionality, by default and intuitively, is entity 1 -> entity 2). Now, whatever I add as entity 1 shows up as child.

**Comment by aepyornis** [comment]
this problem will be (at least partially addressed) by:

[littlesis-browser-addon/issues/20](https://github.com/public-accountability/littlesis-browser-addon/issues/20) and #362
