### ISSUE TITLE
SPIKE: problem submitting education relationship [1]

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#260]
Type: Bug Report
Page: add education page

Description
============
result is an error page and no addition of the info.

Expected Outcome
=================
Increase length of text allowed or give error that field length is too long

**Comment by aguestuser** [comment]
perhaps related to #6

**Comment by aguestuser** [comment]
definition of done: figure out what underlying issue is. if trivial, fix it. if not, make card for fixing it.

**Comment by lovemedicine** [comment]
To fix, create migration to increase field length to 100 and add html form field validation.
