### ISSUE TITLE
SPIKE: determine why add relationship not working [2]

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#261]
# add button not working
> 
> Type: Bug Report
> Page: create a new relationship

> Description
> ============
> I am trying to add a relationship, I put the info into the fields,
> check the org box and the type of org, but when I click add nothing
> happens. If I refresh the page, the info I submitted is gone.
>

**Comment by aepyornis** [comment]
perhaps browser-specific javascript issue?

**Comment by aguestuser** [comment]
resolved by user report.
