### ISSUE TITLE
Federal donation matching process should create new entities for candidates that aren't in system [3]

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-rails#262]
The OpenSecrets matching process should create new LittleSis entities for committees and candidates that are not already in the system. When matching a donor's contributions, it makes sense to include all of the recipients of their contributions in the database, so that data isn't missing. Code should be modified for matching process, but this probably also requires a script to go back through already-matched donors.

**Comment by kconn** [comment]
is this done @aepyornis ?

**Comment by aepyornis** [comment]
not yet

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
