### ISSUE TITLE
A position working for a person shouldn't show up under Business Positions [1]

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-rails#290]
eg, George HW Bush here: https://littlesis.org/person/1381/Francis_S_Blake

previously positions working for people were under "in the office of"
people who worked for the person profiled showed up under "office staff"

but it could just go under the "professional" heading?

**Comment by lizstarin** [comment]
Do we want to return to the "in the office of" convention?

**Comment by lizstarin** [comment]
Actually, I'm digging into this—looks like "in the office of" works correctly, so maybe this is an issue with the data set. Investigating.

**Comment by aepyornis** [comment]
@lizstarin And interestingly enough Francis Blake shows up correctly under staff on Bush's page: https://littlesis.org/person/33277-George_H_W_Bush

**Comment by lizstarin** [comment]
@aepyornis exactly. curious.

**Comment by lizstarin** [comment]
OK, found the problem. I think I need a clarification of our intentions: any person working for any person is "in the office of"? I think my previous assumption was that that applied to working for a politician only. (The problem here is that George HW is both a business person and a politician.)

**Comment by aguestuser** [comment]
> (The problem here is that George HW is both a business person and a politician.)

lols. isn't that just *exactly* the problem here? ;)

**Comment by lizstarin** [comment]
LOL

**Comment by lizstarin** [comment]
@kconn Ziggy and I agreed that "in the office of" means someone working for a government official. We're not going to attempt comparing position dates (for the employee) to dates of elected office (for the employer) to figure out whether someone working for, say, George HWB is doing so in a business or a government capacity. There are just too many positions without dates attached. Instead, we're going to create an is_government? attribute that can be user-modified (checkbox). And if we can auto-check that box unambiguously, we will.

**Comment by aepyornis** [comment]
@kconn @lizstarin and myself decided on a simpler sorting system:  all _person to person_  position relationships will show up as 'in the office of" which makes this all easier.
