### ISSUE TITLE
scripted bulk tagging [2]

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#296]
# ACs

- [x] input spreadsheet
  - entities tab: columns: entity url,  tags, tag-all-related?
  - lists tab: columns: list url, tags, tag-all-in-list?
  - misc tab: columns: entity urls, tags, custom request
- [x] spreadsheet -> csv
- [x] make script
- [ ] run script on prod
- [ ] spot check

# dependencies

* tag set finalized

# out of scope:

* bulk importing relationships

**Comment by aguestuser** [comment]
corner cases:

* a major donor sits on a bunch of boards and gives lots of money. i want to tag him georgia, but i don't necessarily want to tag all his donation recipients as georgia. ie: i want to tag a subset of entities that an entity is related to based on type of relationship
