### ISSUE TITLE
Tag homepage grouped by tabs [2]

### ISSUE THREAD

**Issue by aguestuser** [public-accountability/littlesis-rails#306]
# Acceptance Criteria
* When I visit the "fracking" tags homepage, I will see three tabs at the top of the page: `Entities`, `Lists`, and `Relationship`
* If I click on any tab, I will see a list of elements of that resource type tagged "fracking"

**Comment by kylenstone** [comment]
This card/issue would be easier to grok if named expressively:
`Visiting a tag homepage shows groups of expected content (entities, lists and relationships)`

Apologies for the nitpick comment!  Getting warmed up here.

**Comment by aguestuser** [comment]
@kylenstone nitpick away: that's the role! (and i'm into it.) but the thing about this card is that it augments #234 -- which already groups entities, lists, and relationships in paginated lists on one page -- by instead grouping those 3 categories in tabs. thus the `tab`y-ness is the thing we wished to signal in the title.

**Comment by aguestuser** [comment]
todos left over from review of #312 / #234 👍 

* make `page_params_of` an instance method instead of class method
* refactor tag homepage test setup to reduce # of sql queries
