### ISSUE TITLE
define LsDate date comparisons

### ISSUE THREAD

**Issue by lizstarin** [public-accountability/littlesis-rails#31]

**Comment by lizstarin** [comment]
`<` and `>` mostly work already because of the format, but:
Is `2017-00-00` greater than or less than `2017-03-06`? 
This might depend on context, so maybe this needs to be addressed in the LsDate class, but maybe elsewhere.

**Comment by aepyornis** [comment]
completed by #39 

I decided that the more specific date always is always greater...we can change it later if we think that doesn't work.
