### ISSUE TITLE
Org interlocks tab uses rails [3]

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#334]
# Acceptance Criteria

* see #333 
* description differs: Orgs with Common People | Leadership and staff of `Some Org` also have positions in these orgs

**Comment by aguestuser** [comment]
note to @aepyornis : this PR is paired with a PR to the docker repo that has not yet been merged but needs to be: https://github.com/public-accountability/littlesis-docker/pull/2

^-- removes the nginx rewrite for interlocks
