### ISSUE TITLE
make decision about future of industry pages [1]

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#340]
choices:

1) remove them entirely
2) migration them from symfony before finishing removing symfony
3) hide them from view, pending re-design

the data behind these pages also needs to be updated, which argues for 1 or 3. 

outcome: either do 1 or 3 or write cards for 2. (@aepyornis and @aguestuser counsel 3)

**Comment by kconn** [comment]
are these really in symfony?? I thought they were in rails.

**Comment by aguestuser** [comment]
@kconn @aepyornis and i all agree: 3. closing. but we should probably make a card to implement "hide them from view pending re-design"? it would be like a 1?
