### ISSUE TITLE
add date format instructions on People edit page

### ISSUE THREAD

**Issue by climatebrad** [public-accountability/littlesis-rails#350]
on the edit screen for people should include the "(YYYY-MM-DD. Use 1968-05-00 to specify May 1968)" instructions.

correct:
<img width="648" alt="screen shot 2017-10-04 at 2 34 47 pm" src="https://user-images.githubusercontent.com/6379550/31193121-375fdf68-a911-11e7-838e-e8c24676c666.png">

instructions missing:
<img width="468" alt="screen shot 2017-10-04 at 11 10 01 am" src="https://user-images.githubusercontent.com/6379550/31193002-cf4197dc-a910-11e7-8e79-bcf5d5caff8d.png">

The preferable solution would be for the system to be "smart" and understand other date formats (like "July 7 1986" for 1986-07-07) and only throw errors for ambiguous/malformed dates (like 1/5/1980)

**Comment by aepyornis** [comment]
good idea! we should be able to handle other date formats. 

One small undocumented hint: you can submit just the year '2012'
