### ISSUE TITLE
existing reference link shouldn't populate editing screen in add relationship

### ISSUE THREAD

**Issue by climatebrad** [public-accountability/littlesis-rails#351]
on the Add Relationship page 
if an existing source is selected for the "where this info is coming from" the info shouldn't populate the editable link fields. This behavior seems to be spuriously creating copies of the same source link.

<img width="742" alt="screen shot 2017-10-04 at 2 39 29 pm" src="https://user-images.githubusercontent.com/6379550/31193378-ee8039a4-a911-11e7-86f6-f2fabdd23f17.png">

note the multiple copies of the same reference links here:
<img width="664" alt="screen shot 2017-10-04 at 2 39 10 pm" src="https://user-images.githubusercontent.com/6379550/31193452-25a6ebf8-a912-11e7-96e2-cc2ec4ff9160.png">

Note that the reference-link tool for editing a person or org page functions properly:
<img width="486" alt="screen shot 2017-10-04 at 2 43 02 pm" src="https://user-images.githubusercontent.com/6379550/31193524-5bce455a-a912-11e7-94be-1f59229596e3.png">

The relationship page should have the same 
"Create a new reference" / "Use existing source" toggle behavior as the person page: 
<img width="481" alt="screen shot 2017-10-04 at 2 43 43 pm" src="https://user-images.githubusercontent.com/6379550/31193598-97131294-a912-11e7-8a2d-7e1850e13ae0.png">

**Comment by aepyornis** [comment]
@climatebrad We have updated the UI for on the add a relationship page and have hopefully also solved the duplicate sources issue, which address the issues you raised here. Let use know what you think!
