### ISSUE TITLE
Outside Spending Groups missing partisan tagging

### ISSUE THREAD

**Issue by climatebrad** [public-accountability/littlesis-rails#352]
looks like candidate-related super PACs are missing partisan tagging: e.g. Priorities USA Action or Ready to Rise PAC

<img width="946" alt="screen shot 2017-10-04 at 3 01 38 pm" src="https://user-images.githubusercontent.com/6379550/31194383-072d1a32-a915-11e7-8e13-d6b205d749fd.png">

**Comment by climatebrad** [comment]
OpenSecrets notes these as "single-candidate super PACs" https://www.opensecrets.org/pacs/lookup2.php?strID=C00495861

**Comment by aepyornis** [comment]
@climatebrad Good find! thank you. 

It would be nice to indicate on the chart hat it's both a PAC and of a certain party -- perhaps a two-color stripe on the bar?
