### ISSUE TITLE
expand the options for valid date inputs

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#368]
for instance, it would be nice to accept inputs such as "May 12, 2013" or "June 1999"

related #350

**Comment by robjlucas** [comment]
@aepyornis it's so easy to use a calendar dropdown these days, just by using an HTML5 date field for example, why not offer these wherever there are dates to enter?

**Comment by aepyornis** [comment]
@robjlucas  We could consider that; I've thought about it before. There's a few issues:

- Users often input dates that have a big range. Many calendars date selectors take the assumption that the selected date will be within a few months of the current date. So if you wanted to add a start date in December 1997 it would typically require too many clicks to be practical.

- We allow imprecise dates. 2008-10-00 is valid and understood to mean "October 2008" without indicating what specific day in October. I believe our custom date format doesn't conform to html5 date fields.

None of the calendar widgets I experimented with appeared to work well for our propose. I'm not opposed to the idea, we'd just have to test it out with the staff and users to make sure it improves the editing workflow.

**Comment by robjlucas** [comment]
Thanks @aepyornis. Yeah, I realised after I added this comment that there's a lot of variety in the data that would make a conventional solution tricky. No doubt others have had to negotiate this issue, so perhaps there are solutions out there we could look into again at some point.
