### ISSUE TITLE
SPIKE: gather requirements for moving user pages to rails [2]

### ISSUE THREAD

**Issue by aguestuser** [public-accountability/littlesis-rails#385]
**user page requirements**
* profile picture
* editable 'about me' section (only editable by user, naturally)
* link to user's edits (only visible to admins and that current user)
* show users permissions (only visible to admins and that current user)
* groups that user is a member of (if application)
* profile pages are only visible to signed in users
* add setting on user settings page to disable own profile page
* [bonus] link to 'chat with me' via rocket.chat (if that's even possible)

**Comment by aepyornis** [comment]
See: #396 #397 #398
