### ISSUE TITLE
user page layout in rails [2]

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#396]
### visible to any signed in user:

- [ ]  header with name
- [ ]  profile picture
- [ ] 'about me' text [ editable by user see #397 ]
- [ ] groups that the user is in (if they are in any groups)
- [ ] link to user's modifications page
- [ ]  [_bonus_] link to 'chat with me' via rocket.chat (if that's even possible)

### visible only to the user themselves (and admins)
- [ ] the permissions the user has 

## Out of scope:

* making 'about me' editable --> that's #397

**Comment by lizstarin** [comment]
Which permissions should be listed here? Right now I'm just pulling ALL_PERMISSIONS from the Permissions class.
![permissions](https://user-images.githubusercontent.com/3151071/33389508-0fda4e8a-d501-11e7-8942-5d7f71949e6d.png)
