### ISSUE TITLE
User Configuration Settings [1]

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#397]
## Update the settings page

Currently, users may Modify their settings on this page ``` /users/edit ``` 

Two additional options should be added: a text field with the users 'about me' text and a checkbox indicating if they would like their profile to be visible to any signed user.

### User models changes

- [ ] Add field  `about_me `  (String, opitional)

## page changes:

- [ ] text area for about me

## testing requirements:

- [ ] write requests spec for updating user settings (sadly, one doesn't exist yet 😞)
 
## links and relevant code:

[user settings page](https://littlesis.org/users/edit)
user layout card - #396 

The [UsersController](https://github.com/public-accountability/littlesis-rails/blob/master/app/controllers/users_controller.rb) is not responsible for the users settings page. It's the job of the [Users::RegistrationsController](https://github.com/public-accountability/littlesis-rails/blob/master/app/controllers/users/registrations_controller.rb) which is a  [Devise](https://github.com/plataformatec/devise) controller.

**Comment by lizstarin** [comment]
Do we want "about me" and the photo editable from the settings page, or from the profile page?

**Comment by aepyornis** [comment]
I had suggested that it should be editable from the "settings" page mostly because it's easier for us to implement -- the settings page already updates the user model. But that's certainly up for debate.

**Comment by lizstarin** [comment]
![edit-settings](https://user-images.githubusercontent.com/3151071/33384821-0f6a15ae-d4f5-11e7-96a7-fc3d32f6ce10.png)
![add-image](https://user-images.githubusercontent.com/3151071/33384820-0f43f414-d4f5-11e7-89e0-e9467b8480b2.png)

**Comment by lizstarin** [comment]
Which permissions should be listed here? Right now I'm just pulling ALL_PERMISSIONS from the Permissions class.
![permissions](https://user-images.githubusercontent.com/3151071/33389397-b517fd8a-d500-11e7-9164-7226ac91d325.png)
