### ISSUE TITLE
user modifications page [1]

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#398]
# Users Modifications page

This is page showing all recent edits done by a single user. 

also see #396 #397 

## Requirements

- [x] New route. Something like ` /users/:username/edits ` or ` /users/:username/modifications`
- [x]  page is only viewable by admins or the user themselves
- [x] implement user#recent_edits
- [x] shows table of edits in  use same format as tags edit page

### Development Notes:

The table should be a paginable table that queries``` PaperTrail::Version ```. This could go either on the `UsersController` or on the `EditsController`. 

Right now we don't track changes to NetworkMaps and therefor can't easily track updates to maps. If while making the user modifications page we think it's necessary to include those, let's make a separate card for it.

**Comment by kconn** [comment]
maps?
