### ISSUE TITLE
Redirect merged entities  [2]

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#420]
* merged entities should get redirected to the entity they were merged into
  * **example:** if Jane Smith (id: 123) has been merged with Jane A. Smith (id: 456), then going to ` /person/123-jane_smith ` should send a redirect to ` /person/456-jane_smith `
* all sub-routes for merged entities should also redirect to corresponding sub-route for the entity they have been merged into
  * **example:** in above scenario, `/person/123-jane_smith/political` should redirect to `/person/456-jane_smith`, etc...

**Comment by aguestuser** [comment]
@aepyornis a few questions about implementation:

* presumably we want to handle this in `entities_controller#show` yes?
* how do we want to keep track of an association between an entity and the ids of the entities that have been merged into it? (presumably this requires a new table?)
* presumably we want to keep track of *all* entities that have ever been merged into an entity? (such that if janie smith (id 789) was merged into jane a smith, it would also redirect there?
* what if down the line i merge jane a smith into jane b smith? now presumably all of the ids that ever redirected to jane a smith must also now merge into jane b smith? correct?

**Comment by aepyornis** [comment]
@aguestuser:

> how do we want to keep track of an association between an entity and the ids of the entities that have been merged into it? (presumably this requires a new table?)

This is already tracked. If an entity is merged, then it it will have a merged_id set to be the id of the entity that it's merged into.

> presumably we want to keep track of all entities that have ever been merged into an entity? (such that if janie smith (id 789) was merged into jane a smith, it would also redirect there?

So if Jane Smith (id: 123) has been merged with Jane A. Smith (id: 456) and Jane A. Smith (id: 456) and been merged into Jane B. Smith (id: 789).

then going to /person/123-jane_smith should *redirect to* /person/456-jane_a_smith and that request should *redirect to* /person/789-jane_b_smith

If you implement the redirect it should take care of the multi merged entity problem for automatically.

**Comment by aguestuser** [comment]
cool! so if `merged_id` is already stored and i can recursively redirect, then this seems like a 1. literally just a 1-liner in `entities_controller#show`. or am i missing something?

**Comment by aepyornis** [comment]
@aguestuser -- here's a few more implementation thoughts and considerations:

All merged entity are "soft deleted", which means they won't show up normally via `find`

to return to our example: Jane Smith (id: 123) has been merged with Jane A. Smith (id: 456).

Right now if a request comes if for `/person/123-jane_smith` it will hit [this method](https://github.com/public-accountability/littlesis-rails/blob/master/app/controllers/application_controller.rb#L151-L153):

``` rb
def set_entity
  @entity = Entity.find(params[:id])
end
```
and it will raise ` ActiveRecord::RecordNotFound ` due to the way we've implement soft_delete.

We probably want to change set_entity to do something like this:

``` rb
def set_entity
  @entity = Entity.unscoped.find_by_id(params[:id])
   raise ActiveRecord::RecordNotFound if @entity.nil?
   if @entity.is_deleted and @entity.merged_id.present?
      raise Exceptions::MergedEntity
    else
      raise ActiveRecord::RecordNotFound
    end
end
```

which will still raise RecordNotFound for deleted entities or entities that don't exist, but does something different if the deleted entity has been merged

**Comment by aepyornis** [comment]
also worth mention that it should work redirects for entity routes:

/person/123-jane_smith/interlocks  /person/123-jane_smith/political and so on.

**Comment by aguestuser** [comment]
k. that's super helpful. and yes is enough complexity to warrant a 2.

**Comment by aguestuser** [comment]
(added acceptance criteria about sub-routes to card description above.)
