### ISSUE TITLE
request merge by email [2]

### ISSUE THREAD

**Issue by aguestuser** [public-accountability/littlesis-rails#442]
## Acceptance Criteria

* any signed in user may initiate an entity merge by clicking a button that says `merge` on the **top row** of the entity's profile page
* **if the user is an admin,** they will go through the merging process detailed in  #418 
* **if the user is not an admin**, they will go through the same merging process as admins, except that at the final step (the review merge page), when they click the "merge" button:
  * a pop-up appears informing them that their request has been sent to littlesis admins
  * an email will be sent to all admins with a link to a "merge review" page
  * the request will be recorded to the database (and inspected from the console)

## Out of scope

* reviewing the merge request

## Implementation Notes

To complete this card, we will introduce a `UserRequest` model with (something like) the following fields:

```ruby
@type # :merge | :delete
@status # :pending | :approved | :denied
@user_id # number
@admin_id # number
```

**Comment by kconn** [comment]
UserRequest model should also have timestamps?

**Comment by aguestuser** [comment]
@kconn : it should! but you get that for free with ActiveRecord by virtue of it being a model in the first place. (sort of referenced in implementation notes in #443 )
