### ISSUE TITLE
review merge request page [2]

### ISSUE THREAD

**Issue by aguestuser** [public-accountability/littlesis-rails#443]
## Acceptance Criteria
* when an admin clicks on the link in in a merge request email (see #442 ), they will see a "merge request review page" that shows:
  * the same merge report that the user who requested the merge saw when creating the request (see #418 )
  * a timestamp of the merge request
  * the username who issued request -- hyperlinked to their profile page
  * an `approve` button
  * a `deny` button
* clicking `approve` will:
  * merge the two entities
  * record the approval (and the admin who did the approving) to the database
* clicking `deny` will:
  * leave the two entities unmerged
  * record the denial (and the admin who did the denying) to the databse

**Comment by aguestuser** [comment]
Some loose implementation notes:

## MergeRequest model:

* (will eventually be a subclass of `UserRequest`)
* has fields: @user_id, @source_id, @dest_id, @status, @date_created (implicit)
* @status may be :pending, :approved, :denied
* is created by a POST from the `_merge_request_form` partial
* is read from a GET to the `merge/review` route

## ToolsController

* is still poorly named/segmented IMHO :) (it has all the looks of a runaway file waiting to happen, but that's okay! let's ride the horse while it rides!)
* must now handle following routes: `merge/execute`, `merge/request`, `merge/review`
* on merge routes:
  * must set @merge_mode to either :search, :execute, :request, or :review
  * must set @merge_request if @merge_mode == :review
  * can do this by parsing params or reading active record attributes
* partials will take the logic from there

## Partials

### OPTION 1: 3 wrappers, 1 report, 3 forms:

* `_merge_request` partial
  * renders a `_merge_report` partial with a `_merge_request_form` at the bottom
* `_merge_request_form` partial:
  * submits @source, @dest, timestamp, and user info to `tools/merge/request`
  * `ToolsController#request_merge` handles request and:
    * constructs and persists a `MergeRequest` obj
    * redirects and flashes notification about admins being notified
* `_merge_execution` partial
  * renders a `_merge_report` partial with a `_merge_execution_form` at the bottom
* `_merge_execution_form` partial:
  * does what the form in the current `_merge_mode` partial does (ie: initiates a merge)
* `_merge_review` partial:
  * renders a `_merge_report` partial, but includes some boilerplate at the top:
  * some text about how this is a review of a user's merge
  * some meta-data drawn from the @merge_request (timestamp, username/link)
* _merge_report` partial (formerly `_merge_mode` partial):
  * accepts `merge_form` as a local (which must be supplied by the parent partial)

### OPTION 2: 1 report, 3 forms

* dispatch on @merge_mode and display different form partials accordingly (don't user wrappers)
* optionally include boilerplate directly in `_merge_report` if @merge_mode is :review

### TRADEOFFS:

* OPTION 1 is more declarative, more explicit and possibly more extensible, but bulkier
* OPTION 2 is more elegant, but relies on conditional logic branching that might get out of hand

**Comment by aepyornis** [comment]
@aguestuser  where you thinking that ` MergeRequest ` be it's own table (merge_requests) in the database or will there be one table ( user_requests ) with a type field that will old all different type of user requests ?

**Comment by aepyornis** [comment]
Suggestion: add add a ` skip ` button in case it's not clear if the request should be merged or denied

**Comment by aguestuser** [comment]
good question. i think there is certaily a `UserRequests` object that will currently be polymorphic between `DeleteRequest` and `MergeRequest`, but possibly be polymorphic between many different kinds of requests in the future.

additionally, it is clear that `DeleteRequest` and `MergeRequest` don't have overlapping fields. for example: `MergeRequest` needs to track `@source` and `@dest` (which are irrelevant to a `DeleteRequest`) and a `DeleteRequest` needs to track an `@entity_id` (which is meaningless to a `MergeRequest`).

so that suggests either a sparsely populated `user_requests` table (if we want to do [single table inheritance](https://eewang.github.io/blog/2013/03/12/how-and-when-to-use-single-table-inheritance-in-rails/)), or both a `delete_request` and a `merge_request` table if we wanted to do polymorphic associations. 

do you have a preference or thoughts? (ps: looks like rails 5 supports single table inheritance out of the box: http://api.rubyonrails.org/classes/ActiveRecord/Inheritance.html)

**Comment by aguestuser** [comment]
re: `skip` button -- if it's not clear whether the request should be merged or denied, can't the admin "skip" it by simply closing or navigating away from the review page? why do they need a button to do that? would any additional data be recorded by the admin taking that action? would that data be useful?

once all requests are a queue table, and the admin's workflow is to click on a row to review it and then click on `approve` or `deny` to return back to the page with the table, a `skip` button seems more clearly useful, as without it, it would be more difficult to get back to the queue page if the user doesn't know how to resolve a review. 

so perhaps let's add a skip button once there *is* a table and it would serve a more clearly defined purpose? (ie: pull it in as an AC for card #446 ?)

**Comment by aepyornis** [comment]
I think I have a preference  for a single user_requests table because if we end up having many types of requests I think it'll just get unwieldy to have that many tables, which it might be a little heavy-handed for this type of action. 

I like to ( and maybe i'm just 🐢 _lazy_ 🐢  at OO) of having one table and sticking any additional fields a particular type needs ( i.e. source and dest ) into a JSON blob column which can be deserializes it in the model.

**Comment by aguestuser** [comment]
if i told you that the JSON blob column feels messy (and yes, not very properly OO) to me, would you have another approach you'd like for using a single table?

as to many tables being "unwiedly": is the source of unwieldiness the cost of more SQL statements when retrieving the records for the review queue?

**Comment by aepyornis** [comment]
For the source and dest and entity_id problem you could use a schema like this;

entity1_id
entity2_id 

where for a merge request entity1_id is the source and entity2_id is the dest. for delete request entity1_id becomes the dest entity and entity2_id is just null.

**Comment by aguestuser** [comment]
gah! not more `entity1_id` stuff! names that describe what something is in a way that makes sense in the domain and doesn't require me to hold different secret definitions in my head! by looking at the name i should understand what it is!

**Comment by aepyornis** [comment]
anyways: i shouldn't meddle too much in what you are planning to do. pick whichever approach you think is best 👍

**Comment by aepyornis** [comment]
yes, correct. if we have 5 types of requests we'd need to do either: 5 sql statements or one big join.

**Comment by aguestuser** [comment]
in any case, sounds like straight polymorphic associations is not preferable b/c of multiple tables (possibly a premature performance optimization, but a clearly drawn and logical one). so STI or (maybe i can come around to liking) the JSON blob idea (which is sort of just STI in another guise that would require some slightly fancier deserialization logic and could maybe be made "clean" by giving classes to the kinds of things that come out of the JSON).

**Comment by aepyornis** [comment]
i'm cool with either approach -- which ever you think makes the most since at this point.

**Comment by aguestuser** [comment]
+1 

also realizing: these questions don't really come into play until #445 . right now, there's only a merge request (delete requests don't exist!) so there is only a `merge_requests` table. once there's such a thing as delete requests, let's figure out the best way to extend the idea of merge requests into user requests, and factor in the cost of doing so to estimating #445.

**Comment by aguestuser** [comment]
but for now that's cognitive load we don't need to be carrying to solve the question at hand.
