### ISSUE TITLE
Audit dev environment database anonymization scripts for privacy

### ISSUE THREAD

**Issue by aguestuser** [public-accountability/littlesis-rails#456]
# Problem Statement

* So that contributors and in-house developers may work on LittleSis in a dev environment whose scope and complexity provides an adequate simulation of the production envrionment, Littlesis produces a modified dump of our production database for developers to use when setting up their dev environment. (See [README description](https://github.com/public-accountability/littlesis-main/blob/master/README.md#load-the-development-database))
* To protect the privacy of our users, we take a number of steps to scrub this data of personally identifying information (or other sensitive data) before using the data dump locally. (See [this ruby script](
https://github.com/public-accountability/littlesis-rails/blob/master/lib/task-helpers/development_db.rb) and [this sql script](https://github.com/public-accountability/littlesis-rails/blob/master/lib/sql/clean_users.sql))
* **HOWEVER** because we are not experts in data anonymization, we do not feel comfortable distributing this data dump to anyone other than trusted members of our team.
* **THUS** we cannot empower contributors outside of our inner circle to contribute with a fully-featured development environment, or view core features of the site in action without substantial manual population of datasets

# Proposed Solution

* We are seeking outside contributors with expertise in data anonymization to review the cleaning scripts linked above and suggest ways we might improve them to adequately scrub personally identifying information and thus safely distribute full data dumps to new contributors.
* We are *absolutely* open to hearing that this the completely wrong approach and we should build up a development environment in some other way! 😸

**Comment by aepyornis** [comment]
I'm closing this issue in favor of #1092.
