### ISSUE TITLE
better relationship dates

### ISSUE THREAD

**Issue by lizstarin** [public-accountability/littlesis-rails#471]
It's currently possible to have an end date that is earlier than a start date; this should not be possible.

The presence of an end date should set is_current to false.
(Although the presence of a start date should NOT set is_current to true.)

**Comment by aepyornis** [comment]
somewhat related  #368

**Comment by aepyornis** [comment]
Closing this issue in favor of these two:
- #946 Handle new date string format: Month Day, year 
- #945 Validate end_date and modify is_current accordingly
