### ISSUE TITLE
Parse yaml file and find existing matches

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#480]
## Acceptance criteria

- [x]  parse legislators file and filter out all since 1990
- [x] find matches for entities in database
- [ ] rake tasks which reports matches and missing legislators

### details

This card isn't about creating new entities or updating existing ones. It shouldn't change the database at all. That task is #481. However it should create the code to do the matching.  The rake task should be able to re report how many entities are matched and how many need to be created. It should also be able to list ones that need to be created so we can do human checks on how well the matching is done.

See #470 for more information about the dataset and our data model. A good start for matching legislators is via the ` bioguide_id ` attribute of ` ElectedRepresentative ` 

### design notes

- It might be nice if the entity matching code is made with the idea in mind that it might be extended later to be used for other datasets.

- Consider using ActiveModel or a custom class to represent a Congress-Legisator

- Full test coverage would be ideal for this! If the matching code ends up using sphinx, sphinx can be used in the test environment. [see here](https://github.com/public-accountability/littlesis-rails/blob/master/spec/requests/maps_spec.rb) for an example.

- There's some entity resolution code that already exists which might be able to be repurposed. There's an older, unused class [EntityMatcher](https://github.com/public-accountability/littlesis-rails/blob/master/lib/entity_matcher.rb) and another simple one made recently for cmp data: [Cmp::EntityMatch](https://github.com/public-accountability/littlesis-rails/blob/master/lib/cmp/entity_match.rb)

**Comment by lizstarin** [comment]
#504
