### ISSUE TITLE
Edit date incorrect on entity history page 

### ISSUE THREAD

**Issue by mooninmyname** [public-accountability/littlesis-rails#502]
Last edit to the page has incorrect date. See image attached
<img width="1247" alt="screen shot 2018-01-24 at 12 45 02 pm" src="https://user-images.githubusercontent.com/35738250/35348270-95ebdaea-0105-11e8-9f86-5e32fb179c99.png">

**Comment by aepyornis** [comment]
` last edited by `on the entity page can referrer to either a change to the entity details OR if any of if any of the relationships change.

if you look at the changes under relationships you should see two changes to relationships that did in fact happen in the past day:

![edits_history](https://user-images.githubusercontent.com/8505044/35349015-c949380e-0107-11e8-8c61-43829719daa3.png)

**Comment by aepyornis** [comment]
i'm going to remove this issue since it's referencing an older version of the modification pages. let's open a new one if we find incorrect dates in the system.
