### ISSUE TITLE
Double-counting of federal campaign contributions

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-rails#523]
Joint fundraising contributions – coded as 15z or something in opensecrets data – are currently being counted twice. 

This is how it works: donor A gives donation to pac b; this money is then distributed to a bunch of candidates by pac b but recorded in the FEC/opensecrets data as donations from donor A to the candidates

if you count both donations you double count
if you only count the second you kind of exaggerate the relationship with the candidates
if you only count the first you miss who actually received the money

how shall we resolve?

**Comment by aepyornis** [comment]
see #759

**Comment by climatebrad** [comment]
I think this is the same problem - here's an example
https://littlesis.org/person/420137-Mary_V_Propes

contributions to Trump PAC are listed both as a contribution to the PAC and to Trump
