### ISSUE TITLE
Move edit document page to rails [2]

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#54]
# Acceptance Criteria
- edit reference at url such as : /references/:id/edit
- show link to reference edit page on:
  - entity references list: /entities/:id/references
  - relationship references list (on sidebar of relationship page)

# Context
- on the old symfony references page -- example: https://littlesis.org/person/6634/Carl_C_Icahn/references -- you can edit details about a reference. 
- on the new references page -- https://littlesis.org/entities/110291-Bill_de_Blasio/references -- you cannot edit the references.

**Comment by lizstarin** [comment]
Could we clarify criteria a bit? 
-We're creating the ability to edit DOCUMENTS, not references (so I assume the url should be /documents/:id/edit).
-Do we want any new views other than an edit page?

**Comment by aepyornis** [comment]
@lizstarin Yes, it's the ability to edit documents, not references. I think the original issue was made before a big refactor of our references.

A "view page" for documents is not necessary right now, but you can create a ` DocumentsController ` because eventually I would like there to be a document view page where one could view all the places where a particular document is used on the site (but, that's WAY out-of-scope for this issue!)

all fields should be editable except for URL -- this might be up for debate. @liz pointed about that it might be nice to be able to fix 404 and other broken links. 

additionally these conditions should apply for the field `ref_type`:
- if the document is a fec filing (ref t ype 2) than the ref type should not be editable.
- users shouldn't be able to select FEC filing (ref type 2) as an option for that field

**Comment by lizstarin** [comment]
Page to edit document (still needs a back button and some date box finessing)
![edit-document](https://user-images.githubusercontent.com/3151071/33456866-b8d2b53e-d5ee-11e7-8eae-b899fab08343.png)

Links to edit document page (only show if user is logged in)

on entity sources page:
![entity-source-links](https://user-images.githubusercontent.com/3151071/33456865-b8bd62ec-d5ee-11e7-9491-dab2c53a21be.png)

on relationship sources page:
![relationship-source-link](https://user-images.githubusercontent.com/3151071/33456867-b8de5f60-d5ee-11e7-93a4-69ffb75d2d04.png)

**Comment by lizstarin** [comment]
Another possible AC: 
These edits should be collected under a user's edits, right?
