### ISSUE TITLE
entity profile page pagination for relationship categories can go on for infinity without displaying an error

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#554]
by clicking 'see all' on a relationship category on an entity profile page, you view paginated lists of all relationship for that category. 

for example, ``` /person/41560-Eric_T_Schneiderman?page=2&relationships=donors ```, is page two of donors two Eric Schneiderman.

And although, right now, there are only 4 pages of donations, if you change the url, you can go to, for instance, the 9th page: ``` /person/41560-Eric_T_Schneiderman?page=9&relationships=donors ``` and it will render a blank profile page.

instead going to an invalid page should return an error code or perhaps redirect to page 1?

**Comment by lovemedicine** [comment]
Probably a 404 not found error page should be displayed.
