### ISSUE TITLE
Uploading SVG files doesn't work

### ISSUE THREAD

**Issue by dkg** [public-accountability/littlesis-rails#583]
When i add an image to an entity, i'm allowed to upload an svg file (e.g. corporate or municipal logos).  but when i upload it, the SVG itself odesn't get rendered properly.

You can experiment by uploading a file like 'https://commons.wikimedia.org/wiki/File:NYC_Logo_Wolff_Olins.svg'

**Comment by aepyornis** [comment]
Uploading svg now works! As proof, i uploaded NYC logo to the City of New Yok page: https://littlesis.org/org/223171-City_of_New_York :)
