### ISSUE TITLE
Add ability to add 'Your Entity List' to a user Dashboard 

### ISSUE THREAD

**Issue by joemcl** [public-accountability/littlesis-rails#608]
Add the ability for a user to add an Entity(ies) to a 'Your Entity List' "watchlist" on a user Dashboard, regardless of whether or not the Entity has been edited by the user.

**Comment by aepyornis** [comment]
this is a good suggestion! the the past, we've talked about adding the ability to 'watch an entity'

**Comment by joemcl** [comment]
thanks @aepyornis - so this would be labeled an Enhancement? I can't add labels here.
