### ISSUE TITLE
"Giving" tab on list with individuals & orgs  only displays contributions from individuals

### ISSUE THREAD

**Issue by rcgalbraith** [public-accountability/littlesis-rails#671]
"Giving" tab on this list: https://littlesis.org/lists/2441-uniland-montante/giving appears to show only contributions from individuals on the the list and not organizations.

Also at the top of the tab there is a notification box that reads: "People on this list have the most positions in the following organizations." This appears to be copied from the interlocks tab.

**Comment by aepyornis** [comment]
thanks @rcgalbraith for the bug report!

**Comment by aepyornis** [comment]
Right now, organizations on lists are completely ignored on the interlocks or giving tabs. In fact, if you have a list of only Orgs (example: https://littlesis.org/lists/543-largest-public-colleges-and-universities-2012/members) there is not even an option to view the "Interlocks" or "Giving" tab.

we should consider if it's best change it to include donations from companies as well or have a smarter way to handle lists that have a mix of people and orgs. @kconn might have thoughts on this?
