### ISSUE TITLE
Browser add-on to let users edit LittleSis while on external sites

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-rails#69]
Shorter: A browser add-on that allows LittleSis users to edit the database while on external websites. The LittleSis bookmarklet used to facilitate this kind of editing, but it doesn't seem to work any more. (More about it here: https://littlesis.org/help/addBulk#bookmarklet and here: https://blog.littlesis.org/2011/05/10/introducing-the-littlesis-bookmarklet/)

Longer: Often, when adding information to LittleSis, users are finding data on external websites – say, an organization's board of directors page. An in-page editing tool that allows users to add data to LittleSis while on these other websites is extremely useful, because it cuts down on time spent going back and forth from LittleSis to the external website. 

A pretty standard edit workflow: user finds an interesting relationship on example.com; copies the url; goes over to littlesis.org and begins adding the relationship, entering the url as the reference link; when filling out additional details on the edit relationship page, goes back over to example.com to make sure they have them right (or because the forgot something, like a title or date); fill them out, save the relationship.

An add-on would reduce time spent going back and forth from example.com to littlesis.org. It's a much better user experience, as we saw with the bookmarklet.

With the add-on, the user would still be on example.com and bring up a relationship add form. The form would auto-populate reference link & name, and bring up search boxes for finding the entities in the relationship. The user would search for each name in the relationship, select them or add them in create forms that appear, select a relationship category, and edit the details in the form that appears, all while on the example.com page. 

Possible bonuses:
- auto-detection of entities named on the page (so that
- the ability to lock a particular entity in, so that if you are adding multiple relationships to the same entity you don't have to keep searching for it and selecting it
- add to/edit lists from the add-on page (eg the article is about everyone at a particular party)
- save sources to a person/org's profile using the add-on (eg, you're reading an article about someone and want to save it on the person's profile page for other LittleSis users)
- bulk adds from the add-on page (eg, on an organization's board page, entering the whole board in a text box, setting a relationship category and details, and adding them all at once rather than one by one)

**Comment by miguelpaz** [comment]
Worth checking how Zotero, Genius and Pocket (just joined Mozilla) deal with their add ons. It could speed up your dev process.

**Comment by aepyornis** [comment]
good idea @miguelpaz ! 

it might also be worthwhile to use [WebExtensions](https://developer.mozilla.org/en-US/Add-ons/WebExtensions) in order to make a cross-browser extension.

**Comment by aepyornis** [comment]
https://github.com/public-accountability/littlesis-browser-addon

**Comment by aepyornis** [comment]
Done 👍 Thanks to great work by @lizstarin 

[download chrome extension](https://chrome.google.com/webstore/detail/littlesis-add-on/aomlfehiiambdpbkeegelpbfkjenonhe)

[view code](https://github.com/public-accountability/littlesis-browser-addon)
