### ISSUE TITLE
error merging entity with an external link

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#727]
ActiveRecord::RecordNotUnique (Mysql2::Error: Duplicate entry '283163-1' for key 'index_external_link\
s_on_entity_id_and_link_type': UPDATE `external_links` SET `entity_id` = 283163, `updated_at` = '2018-09-10 17:55:36' WHERE `external_links`.`id` = 31540):

app/utility/entity_merger.rb:28:in `each'
 app/utility/entity_merger.rb:28:in `block in merge!'
app/utility/entity_merger.rb:24:in `merge!'

**Comment by aepyornis** [comment]
```
 Parameters: {
 "mode"=>"execute", "source"=>"120672", "dest"=>"92429", "commit"=>"Merge"}

```
ActiveRecord::RecordNotUnique (Mysql2::Error: Duplicate entry '92429-1' for key 'index_external_links_on_entity_id_and_link_type': UPDATE `external_links` SET `entity_id` = 92429, `updated_at` = '2018-11-01 19:16:59' WHERE `external_links`.`id` = 21127):
```

**Comment by lovemedicine** [comment]
This appears to have been fixed, however a specific error should be shown instead of a generic error page.
