### ISSUE TITLE
Link to littlesis API documentation is broken

### ISSUE THREAD

**Issue by HongPong** [public-accountability/littlesis-rails#730]
Hi Littlesis,

the documentation link threw an error
* http://api.littlesis.org/documentation
* The action you requested produced an internal site error. If you encounter this error repeatedly, please contact us at admin "at" littlesis "dot" you-know-what so we can fix it.

Best regards and keep up all the work!

**Comment by aepyornis** [comment]
Hi @HongPong  Could you tell me which page contained that link?

The correct url for our API documentation is here: https://littlesis.org/api

Thanks!

**Comment by HongPong** [comment]
oh it was on the 1.0 api page http://api.littlesis.org/ .. thank you!

**Comment by aepyornis** [comment]
Sure thing. Closing this issue in favor of #731
