### ISSUE TITLE
Education relationship editor missing options found in the creator

### ISSUE THREAD

**Issue by climatebrad** [public-accountability/littlesis-rails#741]
When you create an education relationship, you can set Degree (drop-down), Field (open text), and Dropout (yes/no/unknown). Those options are missing in the education relationship editor.

**Comment by lovemedicine** [comment]
Degree, Field, and Dropout are now present in the education relationship editor.

**Comment by lovemedicine** [comment]
The relationship editor shows all the fields only after the relationship is first created. If the editor is opened again the fields are missing.

**Comment by robjlucas** [comment]
Can't reproduce this problem so far; the fields seem to be there when I look:

![Screenshot from 2020-07-02 12-35-59](https://user-images.githubusercontent.com/25692779/86354343-c9fe7400-bc60-11ea-8134-098999dbae74.png)
