### ISSUE TITLE
Use redis to store sessions instead of mysql

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#937]

**Comment by robjlucas** [comment]
@aepyornis is it permissable to log all current users out with release of this change, or will we need a transition period during which old sessions are accepted?

**Comment by aepyornis** [comment]
> @aepyornis is it permissable to log all current users out with release of this change, or will we need a transition period during which old sessions are accepted?

yes -- no need to bother trying to convert the mysql stored sessions
