### ISSUE TITLE
Handle new date string format: Month Day, year

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#946]
Handle a common date format: MONTH DAY, YEAR

Examples:

- May 1st, 1970
- April 4, 2000
- Jan 5th 2010

notes:
- comma is optional
- day suffix ('st, 'th) is optional
- Month can be abbreviated

**Comment by willemhb** [comment]
Wrote a vile looking regex to handle this but not sure how to implement it (should it just be added to the list of date regexes in ls_date.rb, or should a method be added to transform matching dates to a cleaner form? Would appreciate some guidance before diving in if possible.

`\A(jan|january|feb|february|mar|march|apr|april|may|june?|july?|aug|august|sept?|september|oct|october|nov|november|dec|december)\.? (\d{1,2})(?:st|nd|rd|th)?,? (\d{4})\Z`

**Comment by aepyornis** [comment]
Hi @willemhb 

There's certainly plenty of long regexes throughout the LittleSis code, so it'll be in good company :)

That's correct -- the best place to implement it is the class method [LsDate.convert](https://github.com/public-accountability/littlesis-rails/blob/master/app/utility/ls_date.rb#L140-L155) and the constant [LsDate::DATE_REGEXES](https://github.com/public-accountability/littlesis-rails/blob/master/app/utility/ls_date.rb#L20-L25). The tests for LsDate are located at [spec/utility/ls_date_spec.rb](https://github.com/public-accountability/littlesis-rails/blob/master/spec/utility/ls_date_spec.rb#L74-L103). 

There might be some client-side javascript validation that could need updating as well, but I can't recall off the top of my head.
